os: linux

language: ruby

notifications:
  email: false

jobs:
  include:
    - language: go
      go: "1.13.x"
      install:
        - go get github.com/munsy/art
        - go get -v .
        - go mod download
      script:
        - go vet -x ./...
        - go test -v -race ./... 
        - go build
        - mkdir -p travis_deploy
        - mv art travis_deploy/
        - mv startup.sh travis_deploy/
      deploy:
        - provider: s3
          access_key_id: $AWS_KEY
          secret_access_key: $AWS_SECRET
          local_dir: travis_deploy
          skip_cleanup: true
          on: &2
            branch: master
          bucket: 'art-production'
          region: 'us-west-1'
        - provider: codedeploy
          access_key_id: $AWS_KEY
          secret_access_key: $AWS_SECRET
          bucket: 'art-production'
          key: latest.zip
          bundle_type: zip
          application: 'art'
          deployment_group: 'art'
          region: us-west-1
          on: *2
    - language: node_js
      node_js: "10"
      cache:
        directories:
          - ./node_modules
      install:
        - npm install
      script:
        - npm run-script build
      deploy:
        - provider: pages
          cleanup: false
          keep_history: true
          token: $GITHUB_TOKEN
          local_dir: dist/site
          on:
            branch: master