sudo: false

language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build

deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    token: $GITHUB_TOKEN
    local_dir: dist/site
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: 'art-production'
    skip_cleanup: true
    on:
      branch: master