sudo: false

language: go

go:
  - 1.13.x

notifications:
  email: false

install:
  - go get github.com/munsy/art
  - go get -v .
  - go get -v github.com/golang/lint/golint

script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go test -v -race ./...