os: linux

language: node_js

notifications:
  email: false

jobs:
  include:
    - language: node_js
      node_js: "10"
      cache:
        directories:
          - ./node_modules
      install:
        - npm install
      script:
        - npm run-script build
      deploy:
        - provider: pages
          skip_cleanup: true
          token: $GITHUB_TOKEN
          local_dir: dist/site
          on:
            branch: master
    - language: go
      go: "1.13.x"
      install:
        - go get github.com/munsy/art
        - go get -v .
        - go mod download
      script:
        - go vet -x ./...
        - go test -v -race ./... 
        - go build
        - mkdir -p dist
        - zip -r art.zip client/ *.go go.* art
        - cp art.zip dist/art.zip
      deploy:
        - provider: s3
          secret_access_key: $AWS_SECRET
          access_key_id: $AWS_KEY
          region: "us-west-2"
          bucket: "art-production"
          local_dir: dist
          cleanup: true
          edge: true
          on:
            branch: master
        - provider: elasticbeanstalk
          description: "travis-deployment"
          secret_access_key: $AWS_SECRET
          access_key_id: $AWS_KEY
          region: "us-west-2"
          app: "art-production"
          env: "art-production"
          bucket: "art-production"
          zip_file: "art.zip"
          skip_cleanup: true
          wait_until_deployed: true
          on:
            branch: master