sudo: false

language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: site/dist
  on:
    branch: master