sudo: false

language: go

go:
  - 1.13.x

notifications:
  email: false

install:
  - go get github.com/munsy/art
  - go get -v .
  - go mod download

script:
  - go vet -x ./...
  - go test -v -race ./...